### ISSUE TITLE
Monte carlo from version 5_0_20191106_0 on does not work under windows

### ISSUE THREAD

**Issue by heyroth** [EMsoft-org/EMsoft#101]
I used your nightly builds to do some EBSD simulations. I started with your example from the wiki.
Using the actual 5.0.2 version I get in the monte carlo simulation the error:
Kernel source length (characters) :                 13566
 ----> Fatal error in routine DoMCsimulation:clCreateProgramWithSource: Error: CL_INVALID_CONTEXT
  Progam ended abnormally
EMMCOpenCL Completed
The 5.0.0 version worked fine.
So I tried EMOpenCLinfo.exe in the different nightly builds:
Up to version  5_0_20191102_0 all is fine. (Output on top of file bug.txt.)
From version 5_0_20191106_0 on I get a endless loop of wrong output.
See bug.txt
[bug.txt](https://github.com/EMsoft-org/EMsoft/files/3893579/bug.txt)

**Comment by imikejackson** [comment]
We have pushed up a fix that seems to work on our local machines. Please try out the nightly build on Thursday NOV 28 to verify the fix does work correctly.

**Comment by heyroth** [comment]
Thank you for your very fast reaction. The new build works fine now.
