### ISSUE TITLE
WSL Ubuntu cmake-error at release(Check size of __int64 - failed;Check size of off64_t - failed)

### ISSUE THREAD

**Issue by luqi-cloud** [EMsoft-org/EMsoft#125]
-- EMsoft_SDK Location: /Software/EMsoft_SDK
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- The Fortran compiler identification is GNU 9.3.0
...
-- Check size of long long
-- Check size of __int64
-- Check size of __int64 - failed
...
-- Check size of off64_t
-- Check size of off64_t - failed
...
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - not found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find BLAS (missing: BLAS_LIBRARIES)

**Comment by elena-pascal** [comment]
You need blas and lapack libraries. I did a pull request with required libraries required on a clean subsystem. 

But more importantly, it will be a struggle to get opencl on WSL. If you manage to let us know.

**Comment by luqi-cloud** [comment]
> You need blas and lapack libraries. I did a pull request with required libraries on a clean subsystem.
> But more importantly, it will be a struggle to get opencl on WSL. If you manage to let us know.



> You need blas and lapack libraries. I did a pull request with required libraries on a clean subsystem.
> But more importantly, it will be a struggle to get opencl on WSL. If you manage to let us know.

Thanks for your quick response. I will try and response the results as soon as possible.

**Comment by luqi-cloud** [comment]
> You need blas and lapack libraries. I did a pull request with required libraries on a clean subsystem.
> But more importantly, it will be a struggle to get opencl on WSL. If you manage to let us know.
> 
> 
> You need blas and lapack libraries. I did a pull request with required libraries on a clean subsystem.
> But more importantly, it will be a struggle to get opencl on WSL. If you manage to let us know.
> 
> Thanks for your quick response. I will try and response the results as soon as possible.

**Comment by luqi-cloud** [comment]
I have installed blas ,lapack and

**Comment by luqi-cloud** [comment]
I have installed intel opencl SDK, blas and lapack libraries. Some bugs disappeared, but checking  size of __int64  still failed. 
...
-- Check size of __int64
-- Check size of __int64 - failed
...
-- Check size of off64_t
-- Check size of off64_t - failed
...
And some new issues occured, :

  CMake Warning at Support/cmp/ExtLib/Qt5Support.cmake:367 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.
 
Qt5 also have to be  installed?  In the  EMsoftSDK , the "Download and Install Qt5" was set OFF.  I change it to 'on'.  Qt5 install error.

**Comment by elena-pascal** [comment]
Qt5 is not stable on newer versions of Ubuntu. If you don't need to use the
Workbench set it off either using ccmake or
-DEMsoft_ENABLE_EMsoftWorkbench=OFF flag
