### ISSUE TITLE
OpenCL.dll not found while trying to run

### ISSUE THREAD

**Issue by goldenanthonykevin** [EMsoft-org/EMsoft#15]
I've tried reinstalling the newest version/installing older versions and all have given me this error message.

![opencl_dll](https://user-images.githubusercontent.com/40897089/42601993-766e8eb0-851c-11e8-8479-efb910698de9.PNG)

**Comment by imikejackson** [comment]
Were you able to fix this by installing the OpenCL driver from NVidia?

**Comment by imikejackson** [comment]
No response from OP so closing as this seems to work in latest 4.1 and 4.2 releases
