### ISSUE TITLE
Missing matlab script for generating binary format files for Dictionary Indexing

### ISSUE THREAD

**Issue by zvy5212** [EMsoft-org/EMsoft#158]
Hi,

I'm learning to use EMsoft these days and I figure out that it's very interesting and powerful. Thank you for developing it!

For Dictionary Indexing, unfortunately, I'm using Aztec so I need to generate the binary format input myself. In the paper (https://doi.org/10.1007/s40192-019-00137-4), it is mentioned that there is a Matlab script for generating the binary files in the supplementary materials. However, I cannot find it there.

Can you help me with finding the Matlab script?

Thanks!

**Comment by zvy5212** [comment]
Thanks a lot! I don't know how to explore patterns as a .ebsp file. But the Matlab code does help me generate the binary file I want. I appreciate it a lot!

**Comment by hakonanes** [comment]
Glad you could generate the binary file!

> explore patterns as a .ebsp file

We support reading of uncompressed .ebsp files in the Python package [kikuchipy](https://kikuchipy.org/en/stable/user_guide/load_save_data.html#Oxford-Instruments-binary). It's based on HyperSpy, so patterns can be [inspected by navigating in a 2D map](https://kikuchipy.org/en/stable/user_guide/visualizing_patterns.html).
