### ISSUE TITLE
EDAX/TSL x pattern center reversed in simulated patterns

### ISSUE THREAD

**Issue by Habakuk224** [EMsoft-org/EMsoft#161]
Hello,

I am trying to reindex a material using DI. However, the DI result is approximately 5° off the original data indexed by Hough indexing in OIM Analysis. After testing of various processing steps, I have discovered, that the pattern center defined in [DItutorial](https://github.com/EMsoft-org/EMsoft/wiki/DItutorial#51-setting-the-detector-geometry) for EDAX systems is probably reversed in x direction. An example follows:

A 120x120 simulation was done by _EMEBSD_ for Euler angles 90, 22, 0 using
```
xpc = 30
ypc = 0
L = 26100
```
for BCC material, i.e. the [100] axis should be perpendicular to the detector. The xpc=30 is a bit extreme, but the error is then easily seen (while for typical xpc close to 0, the effect is barely noticeable).
![x30_y0_E90-22-0](https://user-images.githubusercontent.com/72706923/171902105-758ec3b8-2d32-4818-af40-aaea7d5ec8e3.png)
According to the definition from the DItutorial, this corresponds to
```
x* = 75 %
y* = 50 %
z* = 81.86 %
```
However, when viewed in OIM Analysis (v8) the pattern center defined in such way is shifted from the actual pattern center position on the [100] axis:
![nok](https://user-images.githubusercontent.com/72706923/171902134-7267de64-0063-4c85-891d-929ac56964cf.png)

Correct pattern center is shown for x* = 25 %
![ok](https://user-images.githubusercontent.com/72706923/171902128-1dc4b9b1-8612-4181-9b0b-2fd36b820dfe.png)

Y pattern center is behaving correctly and ypc corresponds to its y* counterpart.

**Comment by marcdegraef** [comment]
Hi,

this was documented for EMsoft 5.0 on 
<https://github.com/EMsoft-org/EMsoft> about half-way down the page:

  *


          *For Dictionary Indexing (DI) users, we have changed our
          convention for EBSD pattern orientation to be the same as the
          vendor convention; i.e., EBSD patterns are displayed looking
          from the detector to the sample. The practical consequence is
          that for older DI runs the sign of the xpc (x-component of
          pattern center) will need to be reversed when used with the
          Release 5.0 indexing programs.*

Regards,
Marc.

**Comment by Habakuk224** [comment]
My mistake, thank you for clarification.

Regards,
Jiri Kozlik
