### ISSUE TITLE
Zero Index rate

### ISSUE THREAD

**Issue by Diego8901** [EMsoft-org/EMsoft#165]
Dear Developers,

I am new to EMsoft. I tried to run dictionary indexing on the Ni example data following the tutorial paper (Integrating Materials and Manufacturing Innovation (2019) 8:226–246). I didn't change any of the parameters but surprisingly got a 0% index rate. It looks like the program failed to read the patterns. Can anybody help me to solve this issue?

I am using the the nightly compiled distributions EMsoft-5.0.20221118.-Win64.zip on Windows 10.

The screenshots are attached.

Thanks a lot.

Jie

![1](https://user-images.githubusercontent.com/51404285/202689771-a1bc99a5-b0dc-44f8-a91c-0890ba6329e5.png)
![2](https://user-images.githubusercontent.com/51404285/202689765-22e3f093-ed76-4f90-9b08-0b7aa9fc7adc.png)
![3](https://user-images.githubusercontent.com/51404285/202689762-284e53b2-de48-4178-80cb-e552d12df7a2.png)
![4](https://user-images.githubusercontent.com/51404285/202689755-ea136996-f6ee-43b6-967c-d81dc051b947.png)
[EMsoft-5.0.20221118.-Win64.zip](http://www.bluequartz.net/binaries/EMsoft/experimental/2022-11-18/EMsoft-5.0.20221118.-Win64.zip)

**Comment by marcdegraef** [comment]
Can you post the namelist file ?

Thanks,
Marc.

**Comment by Diego8901** [comment]
Dear Prof. Graef,

Thanks for the quick reply.

Here are the namelist files I used.
[EMEBSDDI-Ni1_test.txt](https://github.com/EMsoft-org/EMsoft/files/10041263/EMEBSDDI-Ni1_test.txt)
[EMgetADP-Ni1_test.txt](https://github.com/EMsoft-org/EMsoft/files/10041264/EMgetADP-Ni1_test.txt)
[EMEBSDDIpreview-Ni1_test.txt](https://github.com/EMsoft-org/EMsoft/files/10041265/EMEBSDDIpreview-Ni1_test.txt)
[EMEBSDmaster-Ni1_test.txt](https://github.com/EMsoft-org/EMsoft/files/10041266/EMEBSDmaster-Ni1_test.txt)

Jie

**Comment by marcdegraef** [comment]
Can you post the output image of the EMgetADP program ?  Does it look correct?

**Comment by Diego8901** [comment]
Here it is. It looks correct to me.

Seems Github do not support .tiff, so I convert it into a .jpg.

![NiScan1_test_ADP](https://user-images.githubusercontent.com/51404285/202709974-27b55665-490a-43f2-860d-f809c2ae90d3.jpg)

**Comment by marcdegraef** [comment]
can you try and set numsx and numsy to 60 and binning to 1 in the EMEBSDDI namelist file ?

**Comment by Diego8901** [comment]
Thanks, Prof. Graef,

I guess it is working!

Here are some screenshots. Are they correct?
![5](https://user-images.githubusercontent.com/51404285/202712950-a28aef9c-9739-4393-8d03-8a1b40bd48ee.png)
![6](https://user-images.githubusercontent.com/51404285/202712944-e415eef0-9107-4c9f-99b3-2340ee0a9955.png)
![7](https://user-images.githubusercontent.com/51404285/202712937-72b15b82-49c6-4e5d-92fd-2937f655b776.png)

Does this mean that I should always input the pixel dimensions of the pattern (instead of that of the camera) and set the binning to 1?

Jie

**Comment by Diego8901** [comment]
It does not look good again. The index rate is ~14%

![8](https://user-images.githubusercontent.com/51404285/202713896-0d808def-5edf-4b09-a936-8acd6f41340e.png)

**Comment by marcdegraef** [comment]
yes, you should always enter the actual size of the patterns in the experimental file and set binning to 1.

It is possible that you need to change the sign of the pcx pattern center coordinate... there were some changes in the code after the tutorial paper was published, and I think this is one of them...

**Comment by Diego8901** [comment]
I just changed the xpc from 3.4848 to -3.4848 as you suggested. The index rate increased from ~14% to ~15%.

Here is what the IPF looks like.  On the top is the .ang output by EMsoft and the other one is the original data.

![9](https://user-images.githubusercontent.com/51404285/202718315-8f3ee436-4ebe-4123-bee3-9e925ce9ced8.png)

**Comment by marcdegraef** [comment]
ok, the change in the pattern size and binning parameters also requires that you multiply the detector pixel size delta by 8, and that you divide xpc and ypc by 8 ... I think those parameters were valid for the full size patterns and they must be scaled for smaller patterns.

**Comment by Diego8901** [comment]
I didn't realize the connections between these parameters. Now the problem is solved. Thank you very much for your detailed explanation! 

Jie

**Comment by marcdegraef** [comment]
No problem.  Glad to help.

I will close this issue then.
