### ISSUE TITLE
Error (Inconsistent record length, unit 42) Encountered in Using EMEBSDDI

### ISSUE THREAD

**Issue by SimonYHU** [EMsoft-org/EMsoft#173]
Hello, I am trying to use EMsoft to index my data and encountered a error, as shown in the image below.

<img width="1280" alt="Screenshot 2023-06-21 141357" src="https://github.com/EMsoft-org/EMsoft/assets/104898264/cde28664-5cf7-425d-a37b-3db62e1a3295">

My computer system is Windows 11 and the pre-complied bulid is EMsoft-5.0.20220711. The software works smoothly in Monte Carlo and master pattern simulations. To avoid the issue assoicated with my data, I also tried the Ni data given in demo and encountered similar issues.

Is this issue something related to fortran? Could anyone help me to solve this issue?

**Comment by hakonanes** [comment]
Hi @SimonYHU,

there is no explanatory error message, but the error is raised when EMsoft attempts to read your HDF5 file in

https://github.com/EMsoft-org/EMsoft/blob/a45fc42dd7834a595e2605c45958a113ed367a55/Source/EMsoftHDFLib/HDFsupport.f90#L5957

It seems to me that it can open the file, just not read it correctly. Perhaps its related to the width and height of your map you set in the input file (nml)? I don't know...

**Comment by SimonYHU** [comment]
Thanks your reply, @hakonanes. 

I guess the issue probably is arise from the difference in .template format between early version (demo files) and recent version (the one I used). The issue was no longer found after I modified the .template format.

**Comment by hakonanes** [comment]
Good you solved your problem! In that case I suggest to close this issue.

**Comment by leminhngoc13021983** [comment]
Dear SimonYHU,
  I have just started using the EMSOFT software and met the same error as yours.
 Can you instruct me on how you changed the .template format? If so, can you send me your modified file?
Thank you very much.
LE

**Comment by SimonYHU** [comment]
[EMEBSDDI_180.txt](https://github.com/user-attachments/files/16347193/EMEBSDDI_180.txt)
@leminhngoc13021983 , Hi Le, the file attached is a EMEBSDDI file that I used before. Due to the limitation of Github, I changed the file ending into .txt. But remember the EMsoft readable ending should be .nml. 
I guess the main problem about this issue is to use the correct format of template file. The template file provided by Demo may not fit the format needed by latest EMsoft version (Not entirely sure about the true reason). So try to use the format I attached here and change parameters and file ending.
If my file does not work, go to the EMsoft folder you downloaded. Then go to folder 'bin', and then folder 'NamelistTemplates'. The template files provided in 'NamelistTemplates' folder should work. Good luck.

**Comment by leminhngoc13021983** [comment]
Hello,
I have tried configuring my EMEBSDDl file to match your file, but the
program still doesn't run.
However, I discovered another reason: when I set up the full path for '
exptfile', the program runs well.

*! name of datafile where the patterns are stored; path relative to
EMdatapathname*
*         exptfile = 'D:/EBSDAnalysis/DItutorial/EMsoftdata/EDAX-Ni.h5',*

I think that the EMSOFT software didn't correctly find the address of the
'exptfile' file, or the system environment variable of *EMdatapathname *was
set incorrectly.

Now everything works fine.
Thank you very much.
Best regards
------------------------------------------
*Lê Minh Ngọc*

*Mobile:  0171 9065389*
*Tel: +49 3731 393152*
*Address: Olbernhauer str.12, 09599 Freiberg, Deutschland*
*Email:   ***@***.*** ***@***.***>*

*              ***@***.***
***@***.***> ***@***.***>*



Vào Th 3, 23 thg 7, 2024 vào lúc 12:27 SimonYHU ***@***.***>
đã viết:
