### ISSUE TITLE
Problem while running EMMCOpenCL 

### ISSUE THREAD

**Issue by FatimZahraMouhib** [EMsoft-org/EMsoft#177]
Hello,

I want to use EMsoft for pattern simulation and recently installed it. 
When I try to reproduce the monte carlo simulation for Ni from the example I run into the following error:

....
Density, avZ, avA + 8.91125 28.00000, 58.69340
Unkown CL error code: -1001

-----> Fatal error in routine CLinit_PDCCQ:clGetPlatformIDs: Error: Unkown CL error code

Note: the following floating point exceptions are signaling: IEEE_INVALID_FLAG IEEE_DIVIDE_BY_ZERO
STOP Program ended abnormally

Here is my input file:
[EMMCOpenCL.txt](https://github.com/user-attachments/files/15566913/EMMCOpenCL.txt)

It would be great if anyone has an idea how to resolve this.

Regards,
Fatim

**Comment by hakonanes** [comment]
Hi Fatim, Can't say I see anything wrong with your file.

The error `Fatal error in routine CLinit_PDCCQ:clGetPlatformIDs: Error: Unkown CL error code` tells me OpenCL (used by EMsoft) cannot get the IDs of your resources (CPUs and GPUs). I'm afraid I'm not familiar enough with OpenCL to tell you what may cause this error. Hopefully someone else here are.

**Comment by FatimZahraMouhib** [comment]
Hi,
thank you for your reply and the hint.

**Comment by FatimZahraMouhib** [comment]
Hello,
I have this problem since I am using a virtual box.
 I will try to avoid OpenCL applications or  find another place to install EMsoft.
