### ISSUE TITLE
An issue with EBSD indexing

### ISSUE THREAD

**Issue by leminhngoc13021983** [EMsoft-org/EMsoft#180]
Hi everybody,

  I am learning to use the program. However, until the step of Dictionary Indexing, I meet an issue as shown in the following image. Please tell me how to fix it.
 
Thanks,
 Le
![1234](https://github.com/user-attachments/assets/805b395b-bcca-44a8-b981-5915a966d594)
![12345](https://github.com/user-attachments/assets/04ecc533-b910-42e3-a547-9e0224a29493)

**Comment by elena-pascal** [comment]
`*.xtal` files are hdf5 files and they don't like to be accessed by multiple processes unless in very specific circumstances. I am wondering if you have the `Ni.xtal` file opened in another process or something went wrong with it. I would try to 1. make sure nothing else is trying to access the file; 2. if that is true and the issue persists, try to regenerate the xtal file

**Comment by leminhngoc13021983** [comment]
> `*.xtal` files are hdf5 files and they don't like to be accessed by multiple processes unless in very specific circumstances. I am wondering if you have the `Ni.xtal` file opened in another process or something went wrong with it. I would try to 1. make sure nothing else is trying to access the file; 2. if that is true and the issue persists, try to regenerate the xtal file

Exactly as you said.  Because the EMsoftworkbench program was also running, which caused this error.

Thank you.
LE
