### ISSUE TITLE
Wrong column order of x, y in .ang file?

### ISSUE THREAD

**Issue by hwagit** [EMsoft-org/EMsoft#54]
I can read the .ang file produced by `angebsd_writeFile` in `EBSDiomod.f90` in OIM Analysis 7 only _after_ I've change the order of the pattern position columns x, y in the .ang file, by changing the order of when they are written to file.

Before:
```fortran
[...]
! sampling coordinates
    if (sum(ebsdnl%ROI).ne.0) then
      write(str4,'(A,F12.5)') ' ',float(floor(float(ii-1)/float(ebsdnl%ROI(3))))*ebsdnl%StepY
      write(str5,'(A,F12.5)') ' ',float(MODULO(ii-1,ebsdnl%ROI(3)))*ebsdnl%StepX
else
[...]
```
After:
```fortran
[...]
! sampling coordinates
    if (sum(ebsdnl%ROI).ne.0) then
      write(str4,'(A,F12.5)') ' ',float(MODULO(ii-1,ebsdnl%ROI(3)))*ebsdnl%StepX
      write(str5,'(A,F12.5)') ' ',float(floor(float(ii-1)/float(ebsdnl%ROI(3))))*ebsdnl%StepY
    else
[...]
```

Have EDAX changed the order of the x, y columns after version 7 of OIM Analysis?

**Comment by marcdegraef** [comment]
It is possible that the two are interchanged.  I was under the impression that this could be changed in the OIM 7 program itself by redefining the sample reference frame, but it would make more sense to do it in the EMsoft code instead.  I have swapped x and y in the newly committed code.
