### ISSUE TITLE
cmake debug is checking the size of __int64 type for gcc compiler 

### ISSUE THREAD

**Issue by elena-pascal** [EMsoft-org/EMsoft#77]
I'm still on Ubuntu 19.04 and some of the Debug checks on Public are failing (Private one is not building at all for me, so I'm trying to take it step by step). One of them is the fact that it fails to find __int64 which is a Windows type I think.

```
-- Check size of __int64
-- Check size of __int64 - failed
```
Here are my compilers:
```
$ dpkg --list | grep compiler
ii  g++                                              4:8.3.0-1ubuntu3                                     amd64        GNU C++ compiler
ii  g++-8                                            8.3.0-6ubuntu1                                       amd64        GNU C++ compiler
ii  gcc                                              4:8.3.0-1ubuntu3                                     amd64        GNU C compiler
ii  gcc-8                                            8.3.0-6ubuntu1                                       amd64        GNU C compiler
ii  gfortran                                         4:8.3.0-1ubuntu3                                     amd64        GNU Fortran 95 compiler
ii  gfortran-8                                       8.3.0-6ubuntu1                                       amd64        GNU Fortran compiler
```
I'll try to take a look but I don't really know what I'm doing.  Any suggestions would be much appreciated.

**Comment by marcdegraef** [comment]
Hi Elena,

It is possible that all this is due to the version of gcc that you are 
using.  So far, we've been using 6.3, for which everything compiles fine 
on all UNIX-flavored systems.  With gcc-7.3, I know that there is at 
least one problem compiling jsonfortran, which compiles fine with 6.3.  
I have never tried 8, so maybe you could try downgrading to 6.3 and 
recompiling?

Marc.

**Comment by elena-pascal** [comment]
Hi Marc, 

Ok , I installed gcc-6.5 (this is what I had in the repo). I kept version 8 as to not break the rest of my packages. I wiped the previous build and started from scratch. I then generated Makefiles with gcc-6 for the compiler flags for both SDK and EMsoft builds:

```
 CMAKE_C_COMPILER                 /usr/bin/gcc-6                                                                                                                                             
 CMAKE_C_COMPILER_AR              /usr/bin/gcc-ar-6                                                                                                                                          
 CMAKE_C_COMPILER_RANLIB          /usr/bin/gcc-ranlib-6   
```
Nevertheless, when I try to make EMsoft release I get 

```
[  4%] Building Fortran object EMsoftLib/CMakeFiles/EMsoftLib.dir/local.f90.o
/home/elena/EMsoft/EMsoftPublic/EMsoftBuild/Debug/EMsoftLib/local.f90:688:4:

 use json_module
    1
Fatal Error: Cannot read module file ‘json_module.mod’ opened at (1), because it was created by a different version of GNU Fortran
compilation terminated.
```

which is strange since I manually told cmake what to use. I don't really understand what's happening.

I ended up switching the default gcc:
```
$ sudo update-alternatives --config gcc
There are 2 choices for the alternative gcc (providing /usr/bin/gcc).

  Selection    Path            Priority   Status
------------------------------------------------------------
  0            /usr/bin/gcc-8   60        auto mode
* 1            /usr/bin/gcc-6   50        manual mode
  2            /usr/bin/gcc-8   60        manual mode

```
And the build was happy with that. So compiling with gcc-6.5 definitely works. And cmake seems to be calling a the system's default compiler at some point (?)
