### ISSUE TITLE
Indexing 5X5 binning EBSD pattern

### ISSUE THREAD

**Issue by hsheng94** [EMsoft-org/EMsoft#81]
Many of the EBSD pattern using EDAX are collected with optimization -" Reduced noise" which uses a 5 by 5 binning on EBSD camera. However, the EMsoft currently doest not support indexing such patterns. It will be highly appreciated if EMsoft can index 5 by 5 binned patterns. #

**Comment by marcdegraef** [comment]
This is not an issue.  There is a lot of freedom in setting the pattern size.  For instance, let's say that your detector has size 640x480, with pixels of size 50 microns, and you want to get to a 5x binned size of 158x96.   In the EMEBSD program, you can already do that with the following parameters:

delta = 50.0
numsx = 640
numsy = 480
binning = 5

Alternatively, you can avoid binning altogether and directly compute the pattern at the correct size, making sure that you use the correct pixel size:

delta = 250.0
numsx = 158
numsy = 96
binning = 1
